Repository Team-Goraebab/Goraebab-Frontend, pull requests merged in 2024-10, with the labels that each got.

#48 [FEAT] Create Image Modal and Refactoring
  .idea/.gitignore
  .idea/Goraebab-Frontend.iml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/git_toolbox_blame.xml
  .idea/git_toolbox_prj.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/material_theme_project_new.xml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/bar/daemonConnectBar.tsx
  src/components/button/ModalButton.tsx
  src/components/button/addHostButton.tsx
  src/components/button/button.tsx
  src/components/button/largeButton.tsx
  src/components/layout/header.tsx
  src/components/layout/layout.tsx
  src/components/layout/sideBar.tsx
  src/components/modal/image/content/dockerHubContent.tsx
  src/components/modal/image/content/localPathContent.tsx
  src/components/modal/image/imageModal.tsx
  src/components/modal/modal.tsx
  src/components/modal/network/bridgeModal.tsx
Labels: Feat

#55 Fix] Sidebar Hotfix
  src/components/button/largeButton.tsx
  src/components/card/volumeCard.tsx
  src/components/layout/sideBar.tsx
Labels: bug

#60 Fix/modify
  package-lock.json
  package.json
  public/style/style.css
  src/app/(dashboard)/dashboard/page.tsx
  src/app/(management)/management/page.tsx
  src/app/(volume)/volume/page.tsx
  src/app/api/container/kill/route.ts
  src/app/api/container/restart/route.ts
  src/app/api/container/start/route.ts
  src/app/api/container/stats/route.ts
  src/app/api/container/stop/route.ts
  src/app/api/daemon/plugin/disable/route.ts
  src/app/api/daemon/plugin/enable/route.ts
  src/app/api/daemon/plugin/route.ts
  src/app/api/daemon/system/df/route.ts
  src/app/api/daemon/system/prune/route.ts
  src/app/api/daemon/system/route.ts
  src/app/api/daemon/version/route.ts
  src/app/api/image/create/route.ts
  src/app/page.tsx
  src/components/bar/daemonConnectBar.tsx
  src/components/button/button.tsx
  src/components/button/darkModeButton.tsx
  src/components/button/largeButton.tsx
  src/components/card/containerCard.tsx
  src/components/card/imageCard.tsx
  src/components/card/managementCard.tsx
  src/components/card/networkCard.tsx
  src/components/card/volumeCard.tsx
  src/components/layout/header.tsx
  src/components/layout/layout.tsx
  src/components/layout/managementSidebar.tsx
  src/components/layout/sideBar.tsx
  src/components/modal/barOptionModal.tsx
  src/components/modal/container/containerDetailModal.tsx
  src/components/modal/daemon/systemModal.tsx
  src/components/modal/daemon/versionModal.tsx
  src/components/modal/host/hostModal.tsx
  src/components/modal/modal.tsx
  src/components/modal/optionModal.tsx
  src/components/page/builders.tsx
  src/components/page/engine.tsx
  src/components/page/general.tsx
  src/components/page/main.tsx
  src/components/page/notifications.tsx
  src/components/page/resources.tsx
  src/components/table/containerTable.tsx
  src/data/color.ts
  src/data/menu.ts
  src/utils/statusColorsUtils.ts
  tailwind.config.ts
Labels: Feat

#62 [Feat] Help Modal
  package-lock.json
  package.json
  src/app/images/help/helpEx.png
  src/components/contents/help/help1.tsx
  src/components/contents/help/help2.tsx
  src/components/contents/help/help3.tsx
  src/components/contents/help/helpContent.tsx
  src/components/layout/header.tsx
  src/components/modal/helpModal.tsx
Labels: enhancement, Feat

#69 Remote and Feedback
  src/app/api/urlPath.ts
  src/components/button/blueprintButton.tsx
  src/components/button/deleteBlueprintButton.tsx
  src/components/button/panButtons.tsx
  src/components/button/saveButton.tsx
  src/components/card/containerCard.tsx
  src/components/card/containerCardGroup.tsx
  src/components/card/imageCard.tsx
  src/components/card/networkCard.tsx
  src/components/card/volumeCard.tsx
  src/components/layout/sideBar.tsx
  src/components/modal/container/containerModal.tsx
  src/components/modal/daemon/content/mountDetail.tsx
  src/components/modal/daemon/content/mountSettings.tsx
  src/components/modal/image/content/dockerHubContent.tsx
  src/components/modal/image/content/localPathContent.tsx
  src/components/modal/network/bridgeModal.tsx
  src/components/modal/volume/volumeModal.tsx
  src/services/blueprint/api.ts
  src/services/harbor/api.ts
  src/services/remote/database/api.ts
  src/services/remote/docker/api.ts
Labels: enhancement, Feat
